# =============================================================================
# CONFIGURAZIONE GENERALE APPLICAZIONE
# =============================================================================
spring.application.name=auth-service
# Porta dedicata all'Auth Service
server.port=8081

# =============================================================================
# CONFIGURAZIONE DATABASE POSTGRESQL (Utente con permessi CRUD su 'users')
# =============================================================================
spring.datasource.url=jdbc:postgresql://localhost:5432/bugboard_db?currentSchema=bugboard
spring.datasource.username=auth_service_user
spring.datasource.password=auth_sec_pwd

# =============================================================================
# CONFIGURAZIONE HIBERNATE / JPA
# =============================================================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.default_schema=bugboard
spring.autoconfigure.exclude=org.springframework.boot.security.autoconfigure.UserDetailsServiceAutoConfiguration

# =============================================================================
# CONFIGURAZIONE SICUREZZA E JWT
# =============================================================================
jwt.secret=BugBoard26SecretKeyForJwtSigningMustBeAtLeast256BitsLongForHMACSHA256Algorithm
jwt.expiration-ms=86400000
